// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gerrors/errors.proto

package gerrors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GinError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinError) Reset() {
	*x = GinError{}
	mi := &file_ginerrors_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinError) ProtoMessage() {}

func (x *GinError) ProtoReflect() protoreflect.Message {
	mi := &file_ginerrors_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinError.ProtoReflect.Descriptor instead.
func (*GinError) Descriptor() ([]byte, []int) {
	return file_ginerrors_errors_proto_rawDescGZIP(), []int{0}
}

func (x *GinError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GinError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_ginerrors_errors_proto protoreflect.FileDescriptor

const file_ginerrors_errors_proto_rawDesc = "" +
	"\n" +
	"\x16ginerrors/errors.proto\x12\tginerrors\"0\n" +
	"\bGinError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msgb\x06proto3"

var (
	file_ginerrors_errors_proto_rawDescOnce sync.Once
	file_ginerrors_errors_proto_rawDescData []byte
)

func file_ginerrors_errors_proto_rawDescGZIP() []byte {
	file_ginerrors_errors_proto_rawDescOnce.Do(func() {
		file_ginerrors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ginerrors_errors_proto_rawDesc), len(file_ginerrors_errors_proto_rawDesc)))
	})
	return file_ginerrors_errors_proto_rawDescData
}

var file_ginerrors_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ginerrors_errors_proto_goTypes = []any{
	(*GinError)(nil), // 0: gerrors.GinError
}
var file_ginerrors_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ginerrors_errors_proto_init() }
func file_ginerrors_errors_proto_init() {
	if File_ginerrors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ginerrors_errors_proto_rawDesc), len(file_ginerrors_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ginerrors_errors_proto_goTypes,
		DependencyIndexes: file_ginerrors_errors_proto_depIdxs,
		MessageInfos:      file_ginerrors_errors_proto_msgTypes,
	}.Build()
	File_ginerrors_errors_proto = out.File
	file_ginerrors_errors_proto_goTypes = nil
	file_ginerrors_errors_proto_depIdxs = nil
}
