// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ginerrors.proto

package ginerrors

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress ginerrors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PbRPCError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbRPCError) Reset()         { *m = PbRPCError{} }
func (m *PbRPCError) String() string { return proto.CompactTextString(m) }
func (*PbRPCError) ProtoMessage()    {}
func (*PbRPCError) Descriptor() ([]byte, []int) {
	return fileDescriptor_errors_b5bfc263a5925dab, []int{0}
}
func (m *PbRPCError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbRPCError.Unmarshal(m, b)
}
func (m *PbRPCError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbRPCError.Marshal(b, m, deterministic)
}
func (dst *PbRPCError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbRPCError.Merge(dst, src)
}
func (m *PbRPCError) XXX_Size() int {
	return xxx_messageInfo_PbRPCError.Size(m)
}
func (m *PbRPCError) XXX_DiscardUnknown() {
	xxx_messageInfo_PbRPCError.DiscardUnknown(m)
}

var xxx_messageInfo_PbRPCError proto.InternalMessageInfo

func (m *PbRPCError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PbRPCError) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PbRPCError)(nil), "ginerrors.PbRPCError")
}

func init() { proto.RegisterFile("ginerrors.proto", fileDescriptor_errors_b5bfc263a5925dab) }

var fileDescriptor_errors_b5bfc263a5925dab = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2d, 0x2a, 0xca,
	0x2f, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x8c, 0xb8, 0xb8,
	0x02, 0x92, 0x82, 0x02, 0x9c, 0x5d, 0x41, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0xe4, 0xfc, 0x94, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38, 0x5d,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x4c, 0x62, 0x03, 0x1b, 0x61, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x16, 0xe5, 0x7e, 0x63, 0x52, 0x00, 0x00, 0x00,
}
